export const ACTIONS = {
  SEARCH_FOR_CITIES: "SEARCH_FOR_CITIES",
  SEARCH_FOR_LOCATIONS: "SEARCH_FOR_LOCATIONS",
  CITIES_RESPONSE: "CITIES_RESPONSE",
  LOCATIONS_RESPONSE: "LOCATIONS_RESPONSE",
  GET_LOCATION_DETAILS: "GET_LOCATION_DETAILS",
  LOCATION_DETAILS: "LOCATION_DETAILS",
  GET_RESTAURANT: "GET_RESTAURANT",
  RESTAURANT_DETAILS: "RESTAURANT_DETAILS",
  CLEAR_RESTAURANT_DETAILS: "CLEAR_RESTAURANT_DETAILS",
  GET_COLLECTIONS: "GET_COLLECTIONS",
  COLLECTIONS: "COLLECTIONS",
  GET_REVIEWS: "GET_REVIEWS",
  REVIEWS: "REVIEWS",
  CLEAR_FILTERED_RESTAURANTS: "CLEAR_FILTERED_RESTAURANTS",
  GET_FILTERED_RESTAURANTS: "GET_FILTERED_RESTAURANTS",
  FILTERED_RESTAURANTS: "FILTERED_RESTAURANTS",
  GET_ESTABLISHMENTS: "GET_ESTABLISHMENTS",
  ESTABLISHMENTS: "ESTABLISHMENTS",
  GET_CUISINES: "GET_CUISINES",
  CUISINES: "CUISINES",
  FAILURE: "FAILURE"
};

export const API_BASE_URL = "https://developers.zomato.com/api/v2.1/"
